"""change table name request to requests

Revision ID: c0429a4d0c56
Revises: 8cbee3f15f83
Create Date: 2024-04-26 13:06:16.709939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0429a4d0c56'
down_revision = '8cbee3f15f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('message', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_request')
    )
    op.drop_table('requests')
    # ### end Alembic commands ###
